version: '3.8'

networks:
  hodei-network:
    driver: bridge

services:
  # Hodei Server with SQLite (no external DB needed)
  hodei-server-sqlite:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_TYPE: sqlite
    container_name: hodei-server-sqlite
    ports:
      - "50051:50051"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///app/data/hodei.db
    volumes:
      - sqlite-data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
    networks:
      - hodei-network

  # TODO App with SQLite
  todo-app-sqlite:
    build:
      context: .
      dockerfile: examples/todo-app/Dockerfile
      args:
        DATABASE_TYPE: sqlite
    container_name: todo-app-sqlite
    ports:
      - "3000:3000"
    environment:
      - HODEI_ENDPOINT=http://hodei-server-sqlite:50051
      - DATABASE_URL=sqlite:///app/data/todos.db
      - RUST_LOG=info
    volumes:
      - todo-sqlite-data:/app/data
    depends_on:
      hodei-server-sqlite:
        condition: service_healthy
    networks:
      - hodei-network

volumes:
  sqlite-data:
  todo-sqlite-data:
